language: node_js
node_js:
- 10.15.3
branches:
  only:
  - master
script:
- echo "npm test temporarily disabled"
- npm run build
before_deploy:
- export VERSION_NUMBER="1.0.1"
- git tag $VERSION_NUMBER
deploy:
  - provider: releases
    api_key:
      secure: c22c051119482b4fb366ea1047269313a6293717
    file: release.zip
    on:
      branch: master
    skip_cleanup: true