language: node_js
node_js:
  - "10.15."

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

deploy:
  on:
    branch: production